[package]
name = "bevy_template"
version = "0.1.0"
edition = "2021"

[features]
dev = ["bevy-inspector-egui", "bevycheck"]

[dependencies]
bevy-inspector-egui = { version = "0.11.0", optional = true }
bevycheck = { version = "0.3.0", optional = true }

[dependencies.bevy]
version = "0.7.0"
